# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: simon

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/simon/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

brews:
  - repository:
      owner: felixgeelhaar
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/felixgeelhaar/simon"
    description: "AI Agent Governance Runtime - Deterministic control plane for AI agents."
    install: |
      bin.install "simon"

changelog:
  disable: true # Handled by Relicta

release:
  github:
    owner: felixgeelhaar
    name: simon
  draft: true
  prerelease: auto
  mode: append