// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/plugin/proto/simon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Goal             string                 `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	DefinitionOfDone string                 `protobuf:"bytes,2,opt,name=definition_of_done,json=definitionOfDone,proto3" json:"definition_of_done,omitempty"`
	Constraints      []string               `protobuf:"bytes,3,rep,name=constraints,proto3" json:"constraints,omitempty"`
	Evidence         []string               `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_simon_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *ValidateRequest) GetDefinitionOfDone() string {
	if x != nil {
		return x.DefinitionOfDone
	}
	return ""
}

func (x *ValidateRequest) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *ValidateRequest) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_simon_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ValidateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                                                             // e.g. "run_shell"
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. {"cmd": "rm -rf /"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_simon_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type CheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allowed          bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	ViolationRule    string                 `protobuf:"bytes,2,opt,name=violation_rule,json=violationRule,proto3" json:"violation_rule,omitempty"`
	ViolationMessage string                 `protobuf:"bytes,3,opt,name=violation_message,json=violationMessage,proto3" json:"violation_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_simon_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetViolationRule() string {
	if x != nil {
		return x.ViolationRule
	}
	return ""
}

func (x *CheckResponse) GetViolationMessage() string {
	if x != nil {
		return x.ViolationMessage
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_simon_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Simplified for proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_simon_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_simon_proto_rawDescGZIP(), []int{6}
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_simon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_simon_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

var File_internal_plugin_proto_simon_proto protoreflect.FileDescriptor

const file_internal_plugin_proto_simon_proto_rawDesc = "" +
	"\n" +
	"!internal/plugin/proto/simon.proto\x12\x05proto\"\x91\x01\n" +
	"\x0fValidateRequest\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\tR\x04goal\x12,\n" +
	"\x12definition_of_done\x18\x02 \x01(\tR\x10definitionOfDone\x12 \n" +
	"\vconstraints\x18\x03 \x03(\tR\vconstraints\x12\x1a\n" +
	"\bevidence\x18\x04 \x03(\tR\bevidence\"\\\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\x9e\x01\n" +
	"\fCheckRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12:\n" +
	"\acontext\x18\x02 \x03(\v2 .proto.CheckRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12%\n" +
	"\x0eviolation_rule\x18\x02 \x01(\tR\rviolationRule\x12+\n" +
	"\x11violation_message\x18\x03 \x01(\tR\x10violationMessage\"9\n" +
	"\vChatRequest\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.proto.MessageR\bmessages\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"L\n" +
	"\fChatResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\"\n" +
	"\x05usage\x18\x02 \x01(\v2\f.proto.UsageR\x05usage\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens2D\n" +
	"\x05Coach\x12;\n" +
	"\bValidate\x12\x16.proto.ValidateRequest\x1a\x17.proto.ValidateResponse2;\n" +
	"\x05Guard\x122\n" +
	"\x05Check\x12\x13.proto.CheckRequest\x1a\x14.proto.CheckResponse2;\n" +
	"\bProvider\x12/\n" +
	"\x04Chat\x12\x12.proto.ChatRequest\x1a\x13.proto.ChatResponseB6Z4github.com/felixgeelhaar/simon/internal/plugin/protob\x06proto3"

var (
	file_internal_plugin_proto_simon_proto_rawDescOnce sync.Once
	file_internal_plugin_proto_simon_proto_rawDescData []byte
)

func file_internal_plugin_proto_simon_proto_rawDescGZIP() []byte {
	file_internal_plugin_proto_simon_proto_rawDescOnce.Do(func() {
		file_internal_plugin_proto_simon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_simon_proto_rawDesc), len(file_internal_plugin_proto_simon_proto_rawDesc)))
	})
	return file_internal_plugin_proto_simon_proto_rawDescData
}

var file_internal_plugin_proto_simon_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_plugin_proto_simon_proto_goTypes = []any{
	(*ValidateRequest)(nil),  // 0: proto.ValidateRequest
	(*ValidateResponse)(nil), // 1: proto.ValidateResponse
	(*CheckRequest)(nil),     // 2: proto.CheckRequest
	(*CheckResponse)(nil),    // 3: proto.CheckResponse
	(*ChatRequest)(nil),      // 4: proto.ChatRequest
	(*Message)(nil),          // 5: proto.Message
	(*ChatResponse)(nil),     // 6: proto.ChatResponse
	(*Usage)(nil),            // 7: proto.Usage
	nil,                      // 8: proto.CheckRequest.ContextEntry
}
var file_internal_plugin_proto_simon_proto_depIdxs = []int32{
	8, // 0: proto.CheckRequest.context:type_name -> proto.CheckRequest.ContextEntry
	5, // 1: proto.ChatRequest.messages:type_name -> proto.Message
	7, // 2: proto.ChatResponse.usage:type_name -> proto.Usage
	0, // 3: proto.Coach.Validate:input_type -> proto.ValidateRequest
	2, // 4: proto.Guard.Check:input_type -> proto.CheckRequest
	4, // 5: proto.Provider.Chat:input_type -> proto.ChatRequest
	1, // 6: proto.Coach.Validate:output_type -> proto.ValidateResponse
	3, // 7: proto.Guard.Check:output_type -> proto.CheckResponse
	6, // 8: proto.Provider.Chat:output_type -> proto.ChatResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_plugin_proto_simon_proto_init() }
func file_internal_plugin_proto_simon_proto_init() {
	if File_internal_plugin_proto_simon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_simon_proto_rawDesc), len(file_internal_plugin_proto_simon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_plugin_proto_simon_proto_goTypes,
		DependencyIndexes: file_internal_plugin_proto_simon_proto_depIdxs,
		MessageInfos:      file_internal_plugin_proto_simon_proto_msgTypes,
	}.Build()
	File_internal_plugin_proto_simon_proto = out.File
	file_internal_plugin_proto_simon_proto_goTypes = nil
	file_internal_plugin_proto_simon_proto_depIdxs = nil
}
